version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk-s3
    versions:
    - 1.93.1
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.0.3.5
    - 6.0.3.6
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: omniauth
    versions:
    - 2.0.1
    - 2.0.2
    - 2.0.3
  - dependency-name: carrierwave
    versions:
    - 2.1.1
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: webpacker
    versions:
    - 5.2.1
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: websocket-extensions
    versions:
    - 0.1.5
  - dependency-name: kaminari
    versions:
    - 1.2.1
  - dependency-name: puma
    versions:
    - 4.3.5
  - dependency-name: rubocop-rails
    versions:
    - 2.5.2
  - dependency-name: annotate
    versions:
    - 3.1.1
