version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app:cached
      - bundle_install:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    command:
      bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    tty:
      true
  db:
    image: postgres:11.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
volumes:
  bundle_install:
    driver: local
